import type { GTR30Employee, GTR30FormData, GTR30PostItem, GTR30TransitItem } from '../types';

export const createDefaultEmployee = (srNo = 1): GTR30Employee => ({
  id: crypto.randomUUID(),
  srNo,
  name: 'Shri R.B.Makvana',
  designation: 'Research Assistant',
  designationGujarati: 'સંશોધન મદદનીશ',
  cadreClass: '3',
  payScale: '34,500-1,12,400',
  gradePay: 'GP:4200',
  payLevelCell: 'PAY=39900 (LEVEL CELL-7)',
  ppaNo: 'Applied',
  quarterAddress: 'H-7, Government Quarters, Khatodara, Nr. Sub Jail, Surat',
  insuranceGroup: 'ખ',
  insuranceType: 'savings_and_insurance',

  payOfOfficer: 0,
  payOfEstablishment: 42300,
  nppa: 0,
  leaveSalary: 0,
  leaveEncashment: 0,
  dearnessPay: 0,
  da: 25380,
  hra: 0,
  cla: 270,
  otherAllowance: 0,
  medicalAllowance: 1000,
  bonus: 0,
  pta: 0,
  profSplService: 0,
  washingAllowance: 0,
  officeExpenseOther: 0,
  ca: 0,
  transportAllowance: 3600,
  ropArrearsGaz: 0,
  ropArrearsNonGaz: 0,
  dpGaz: 0,
  dpNonGaz: 0,

  recovFestivalAdv: 0,
  recovFoodGrainAdv: 0,
  recovPay: 0,
  leaveSalaryAdv: 0,

  incomeTax: 0,
  surchargeIT: 0,
  housingFund: 0,
  rentOfBuilding: 300,
  policeHousing: 0,
  postalLifeInsurance: 0,
  bsiPremium: 0,
  professionalTax: 200,
  gis1979Insurance: 0,
  gis1981Insurance: 240,
  gis1981Savings: 560,
  aisInsurance: 0,
  aisSavings: 0,
  diviAcctInsurance: 0,
  diviAcctSavings: 0,
  pfDeputation: 0,
  govtHousingFund: 0,
  hba: 0,
  motorCarAdv: 0,
  securityDeposit: 0,
  iasProvidentFund: 0,
  gpfOtherThanClass4: 0,
  gpfDiviAcct: 0,
  contributoryPF: 0,
  gpfWorkCharged: 0,
  gpfRojamdar: 0,
  festivalAdv: 0,
  foodGrainAdv: 0,
  fanAdv: 0,
  otherConveyanceAdv: 0,
  interestOnAdv: 0,
  jeepRent: 0,
  pfAdjustableByAO: 0,
  recovPayLeaveSalary: 0,
  miscRecoveries: 0,
  npsPension: 6768,
  societyDeduction: 4154,
  remarks: '',
});

export const defaultTransitItems: GTR30TransitItem[] = [
  { srNo: '', date: '', tokenNo: '', tokenDate: '' },
  { srNo: '', date: '', tokenNo: '', tokenDate: '' },
  { srNo: '', date: '', tokenNo: '', tokenDate: '' },
];

export const defaultEstablishmentPosts: GTR30PostItem[] = [
  {
    id: 'post-1',
    srNo: '૧',
    designation: 'આંકડા અધિકારી',
    cadreClass: '૨',
    sanctioned: 1,
    filled: 0,
    vacant: 1,
    total: 1,
  },
  {
    id: 'post-2',
    srNo: '૨',
    designation: 'સંશોધન મદદનીશ',
    cadreClass: '૩',
    sanctioned: 1,
    filled: 1,
    vacant: 0,
    total: 1,
  },
  {
    id: 'post-3',
    srNo: '૩',
    designation: 'આંકડા મદદનીશ',
    cadreClass: '૩',
    sanctioned: 1,
    filled: 0,
    vacant: 1,
    total: 1,
  },
];

export const sampleGTR30FormData: GTR30FormData = {
  billRegisterNo: 'GTR30-2026-27/01',
  billDate: '21-08-2026',
  monthOf: 'July-2026',
  billCode: 'GTR30-SAL',
  monthYearDigits: '0726',
  district: '66',
  branchName: 'એક શાખા',
  officeName: 'Dy. Dir. of A.H., I.C.D.P., Surat',
  officeFullName: 'Deputy Director of A.H., Intensive Cattle Development Programme, Nanpura, Surat.',
  treasuryName: 'District Treasury, SURAT.',
  phoneNo: '0261-2464658',
  cardexNo: '22',
  ddoCode: '299',
  station: 'Surat',
  controllingOfficer: '',
  classOfExpenditure: '1',
  fund: '3',
  drawingOfficer: '299',
  demandNo: '004',
  typeOfBudget: '1',
  schemeNo: '0000000',
  headChargeable: '2403001139900',
  sector: 'Sector-C-Economic Service',
  demandNoLabel: 'Demand No. 004',
  majorHead: 'Major Head-2403 Animal Husbandry',
  minorHead: 'Minor Head-113 Administative Investigation and Statistcs',
  subHead:
    'Sub Head-99 Scheme for Strengthening of Statistical Wing in Directorate of Animal Husbandry (Pay and Allowances for Centrally Sponsored Scheme)',
  budgetYear: '2026-27',
  budgetAllotment: 0,
  schemeResolutionText:
    'કૃષિ,ખેડુત કલ્યાણ અને સહકાર વિભાગના ઠરાવ ક્રમાંક:ACD/MSM/e-file/2/2026/1756/P1 Dt.22-06-2026 થી સદર યોજના તા:૦૧-૦૩-૨૦૨૬ થી તા:૨૮-૦૨-૨૦૨૭ સુધી ચાલુ રાખવાની મંજુરી મળેલ છે.',
  daResolutionText:
    'સરકારશ્રીના નાણાં વિભાગ, સચિવાલય, ગાંધીનગરના ઠરાવ ક્રમાંક:- વલભ-૧૦૨૦૧૬-જીઓઆઈ-૭-ચ તારીખ:- ૦૪-૧૨-૨૦૨૪ થી સાતમો પગાર પંચ મુજબ ૬૦% ડીએ આકારેલ છે.',
  drawingOfficerName: 'Smt. S.V.Solanki.',
  drawingOfficerNameGujarati: 'શ્રીમતિ એસ.વી.સોલંકી',
  drawingOfficerDesignation: 'Assistant Administrative Cum Account Officer',
  drawingOfficerDesignationGujarati: 'મદદનીશ વહીવટી સહ હિસાબી અધિકારી',
  drawingOfficerOffice: 'Intensive Cattle Development Programme, Surat.',
  drawingOfficerOfficeGujarati: 'ઘ.પ.સુ.યોજના-સુરત',
  messengerName: 'SMT S.K.RANDERI',
  messengerDesignation: 'Junior Clerk',
  transits: defaultTransitItems,
  establishmentPosts: defaultEstablishmentPosts,
  employees: [createDefaultEmployee(1)],
};

export const DEFAULT_BILL_CODE_MAPPINGS = [
  { id: 'bc-1', billCode: 'GTR30-SAL', description: 'GTR-30 Salary Bill' },
  { id: 'bc-2', billCode: 'GTR30-DA', description: 'GTR-30 DA Arrears' },
  { id: 'bc-3', billCode: 'GTR30-BONUS', description: 'GTR-30 Bonus' },
];
