import type {
  GTR30Employee,
  GTR30FormData,
  GTR30PostItem,
  GTR30TransitItem,
  GTR30BillCodeMapping,
  GTR30BudgetHead,
} from '../types';

export const createDefaultEmployee = (srNo = 1): GTR30Employee => ({
  id: crypto.randomUUID(),
  srNo,
  name: '',
  designation: '',
  designationGujarati: '',
  cadreClass: '3',
  payScale: '',
  gradePay: '',
  payLevelCell: '',
    ppaNo: '',
  ph: '',
  slo: '',
  quarterAddress: '',
  insuranceGroup: 'ખ',
  insuranceType: 'savings_and_insurance',

  payOfOfficer: 0,
  payOfEstablishment: 0,
  nppa: 0,
  leaveSalary: 0,
  leaveEncashment: 0,
  dearnessPay: 0,
  da: 0,
  hra: 0,
  cla: 0,
  otherAllowance: 0,
  medicalAllowance: 0,
  bonus: 0,
  pta: 0,
  profSplService: 0,
  washingAllowance: 0,
  officeExpenseOther: 0,
  ca: 0,
  transportAllowance: 0,
  ropArrearsGaz: 0,
  ropArrearsNonGaz: 0,
  dpGaz: 0,
  dpNonGaz: 0,

  recovFestivalAdv: 0,
  recovFoodGrainAdv: 0,
  recovPay: 0,
  leaveSalaryAdv: 0,

  incomeTax: 0,
  surchargeIT: 0,
  housingFund: 0,
  rentOfBuilding: 0,
  policeHousing: 0,
  postalLifeInsurance: 0,
  bsiPremium: 0,
  professionalTax: 0,
  gis1979Insurance: 0,
  gis1981Insurance: 0,
  gis1981Savings: 0,
  aisInsurance: 0,
  aisSavings: 0,
  diviAcctInsurance: 0,
  diviAcctSavings: 0,
  pfDeputation: 0,
  govtHousingFund: 0,
  hba: 0,
  motorCarAdv: 0,
  securityDeposit: 0,
  iasProvidentFund: 0,
  gpfOtherThanClass4: 0,
  gpfDiviAcct: 0,
  contributoryPF: 0,
  gpfWorkCharged: 0,
  gpfRojamdar: 0,
  festivalAdv: 0,
  foodGrainAdv: 0,
  fanAdv: 0,
  otherConveyanceAdv: 0,
  interestOnAdv: 0,
  jeepRent: 0,
  pfAdjustableByAO: 0,
  recovPayLeaveSalary: 0,
  miscRecoveries: 0,
  npsPension: 0,
  societyDeduction: 0,
  remarks: '',
});

/**
 * A blank employee row for manual entry — no sample/personal data pre-filled.
 * Structural defaults (pay-scale catalog values, GIS group, cadre class) are
 * kept; every identity and money field starts empty so nothing is billed by
 * accident. DA/NPS auto-recalculate once basic pay is entered.
 */
export const createBlankEmployee = (srNo = 1): GTR30Employee => ({
  ...createDefaultEmployee(srNo),
});

export const defaultTransitItems: GTR30TransitItem[] = [
  { srNo: '', date: '', tokenNo: '', tokenDate: '' },
  { srNo: '', date: '', tokenNo: '', tokenDate: '' },
  { srNo: '', date: '', tokenNo: '', tokenDate: '' },
];

export const defaultEstablishmentPosts: GTR30PostItem[] = [
  {
    id: 'post-1',
    srNo: '૧',
    designation: 'આંકડા અધિકારી',
    cadreClass: '૨',
    sanctioned: 1,
    filled: 0,
    vacant: 1,
    total: 1,
  },
  {
    id: 'post-2',
    srNo: '૨',
    designation: 'સંશોધન મદદનીશ',
    cadreClass: '૩',
    sanctioned: 1,
    filled: 1,
    vacant: 0,
    total: 1,
  },
  {
    id: 'post-3',
    srNo: '૩',
    designation: 'આંકડા મદદનીશ',
    cadreClass: '૩',
    sanctioned: 1,
    filled: 0,
    vacant: 1,
    total: 1,
  },
];

export const sampleGTR30FormData: GTR30FormData = {
  billRegisterNo: '',
  billDate: '',
  monthOf: '',
  billCode: '',
  monthYearDigits: '',
  district: '',
  branchName: '',
  officeName: '',
  officeFullName: '',
  treasuryName: '',
  phoneNo: '',
  cardexNo: '',
  ddoCode: '',
  station: '',
  controllingOfficer: '',
  classOfExpenditure: '',
  fund: '',
  drawingOfficer: '',
  demandNo: '',
  typeOfBudget: '',
  schemeNo: '',
  headChargeable: '',
  sector: '',
  demandNoLabel: '',
  majorHead: '',
  minorHead: 'Minor Head-113 Administrative Investigation and Statistics',
  subHead: '',
  budgetYear: '',
  budgetAllotment: 0,
  schemeResolutionText: '',
  daResolutionText: '',
  drawingOfficerName: '',
  drawingOfficerNameGujarati: '',
  drawingOfficerDesignation: '',
  drawingOfficerDesignationGujarati: '',
  drawingOfficerOffice: '',
  drawingOfficerOfficeGujarati: '',
  messengerName: '',
  messengerDesignation: '',
  transits: defaultTransitItems,
  establishmentPosts: defaultEstablishmentPosts,
  employees: [createBlankEmployee(1)],
};

export const DEFAULT_BILL_CODE_MAPPINGS: GTR30BillCodeMapping[] = [
  {
    id: 'bc-1',
    billCode: 'GTR30-SAL',
    description: 'GTR-30 Regular Salary Bill',
    controllingOfficer: '0101',
    classOfExpenditure: '1',
    fund: '3',
    drawingOfficer: '299',
    demandNo: '004',
    typeOfBudget: '1',
    schemeNo: '0000000',
    headChargeable: '2403001139900',
    sector: 'Sector-C-Economic Service',
    majorHead: 'Major Head-2403 Animal Husbandry',
    subMajorHead: '-',
minorHead: 'Minor Head-113 Administrative Investigation and Statistics',
  subHead:
    'Sub Head-05 Scheme for Strengthening of Statistical Wing in Directorate of Animal Husbandry (Pay and Allowances for Centrally Sponsored Scheme)',
  budgetYear: '2026-27',
},
{
  id: 'bc-2',
  billCode: 'GTR30-DA',
  description: 'GTR-30 DA Arrears Bill',
  controllingOfficer: '0101',
  classOfExpenditure: '1',
  fund: '3',
  drawingOfficer: '299',
  demandNo: '004',
  typeOfBudget: '1',
  schemeNo: '0000000',
  headChargeable: '2403001139900',
  sector: 'Sector-C-Economic Service',
  majorHead: 'Major Head-2403 Animal Husbandry',
  subMajorHead: '-',
  minorHead: 'Minor Head-113 Administrative Investigation and Statistics',
  subHead:
    'Sub Head-05 Scheme for Strengthening of Statistical Wing in Directorate of Animal Husbandry (Pay and Allowances for Centrally Sponsored Scheme)',
  budgetYear: '2026-27',
},
{
  id: 'bc-3',
  billCode: 'GTR30-BONUS',
  description: 'GTR-30 Ad-hoc Bonus Bill',
  controllingOfficer: '0101',
  classOfExpenditure: '1',
  fund: '3',
  drawingOfficer: '299',
  demandNo: '004',
  typeOfBudget: '1',
  schemeNo: '0000000',
  headChargeable: '2403001139900',
  sector: 'Sector-C-Economic Service',
  majorHead: 'Major Head-2403 Animal Husbandry',
  subMajorHead: '-',
  minorHead: 'Minor Head-113 Administrative Investigation and Statistics',
  subHead:
    'Sub Head-05 Scheme for Strengthening of Statistical Wing in Directorate of Animal Husbandry (Pay and Allowances for Centrally Sponsored Scheme)',
  budgetYear: '2026-27',
},
];

export const DEFAULT_BUDGET_HEADS: GTR30BudgetHead[] = [
  {
    id: 'bh-1',
    name: 'Statistical Wing (CSS) — Pay & Allowances',
    headChargeable: '2403001139900',
    controllingOfficer: '0101',
    classOfExpenditure: '1',
    fund: '3',
    drawingOfficer: '299',
    demandNo: '004',
    typeOfBudget: '1',
    schemeNo: '0000000',
    sector: 'Sector-C-Economic Service',
    majorHead: 'Major Head-2403 Animal Husbandry',
    subMajorHead: '-',
    minorHead: 'Minor Head-113 Administrative Investigation and Statistics',
    subHead:
      'Sub Head-05 Scheme for Strengthening of Statistical Wing in Directorate of Animal Husbandry (Pay and Allowances for Centrally Sponsored Scheme)',
    budgetYear: '2026-27',
  },
];
