import {
  LayoutDashboard,
  Users,
  FileBarChart,
  Settings,
  Clock,
  Receipt,
  FileSpreadsheet,
  Upload,
  Layers,
  FilePlus,
  BarChart3,
  UserCheck,
  Calculator,
  Sliders,
  FileText,
  CreditCard,
  Sparkles,
  ScanText,
  Merge,
  Split,
  RotateCw,
  Minimize2,
  Stamp,
  Images,
  Image as ImageIcon,
  Languages,
  Cpu,
  History,
  type LucideIcon,
} from 'lucide-react';

const SECTION_ICONS: Record<string, LucideIcon> = {
  overview: LayoutDashboard,
  users: Users,
  reports: FileBarChart,
  audit: Clock,
  upload: Upload,
  layers: Layers,
  'file-plus': FilePlus,
  receipt: Receipt,
  settings: Settings,
  sliders: Sliders,
  calculator: Calculator,
  'file-spreadsheet': FileSpreadsheet,
  'bar-chart': BarChart3,
  user: UserCheck,
  'file-text': FileText,
  'credit-card': CreditCard,
  'scan-text': ScanText,
  sparkles: Sparkles,
  merge: Merge,
  split: Split,
  'rotate-cw': RotateCw,
  'minimize-2': Minimize2,
  stamp: Stamp,
  images: Images,
  image: ImageIcon,
  languages: Languages,
  cpu: Cpu,
  history: History,
};

const FALLBACK_ICON: LucideIcon = LayoutDashboard;

export function getSectionIcon(id: string): LucideIcon {
  return SECTION_ICONS[id] || FALLBACK_ICON;
}
