export interface EstablishmentPostOption {
  name: string;
  payLevel: string;
  minPay: number;
  gujaratiName?: string;
}

/**
 * Cadre/post catalogue supplied from the Establishment sanctioned-strength
 * statement. Keep this order stable because it mirrors the source document.
 */
export const ESTABLISHMENT_POST_OPTIONS: EstablishmentPostOption[] = [
  { name: 'પટાવાળા વર્ગ-૪', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'હવાલદાર', payLevel: 'IS, 3', minPay: 15700 },
  { name: 'નાયક', payLevel: 'IS, 2', minPay: 15000 },
  { name: 'ડ્રેસર', payLevel: 'IS, 3', minPay: 15700 },
  { name: 'દફતરબંધ', payLevel: 'IS, 2', minPay: 15000 },
  { name: 'એટેન્ડન્ટ', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'ભરવાડ', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'ચોકીદાર', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'નંદી સેવક', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'સાયસ', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'મુખ્ય સાયસ', payLevel: 'IS, 3', minPay: 15700 },
  { name: 'બોટ ચાકર', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'લેબોરેટરી એટેન્ડન્ટ', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'સ્વીપર', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'સાથી', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'ગોવાળ', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'કેરિયર', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'ક્લીનર', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'પેકર', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'પટાવાળા કમ હમાલ', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'કોચમેન', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'વિલેજ લેવલ વર્કર', payLevel: 'Level 2', minPay: 19900 },
  { name: 'એક્સરે ટેકનિશિયન', payLevel: 'Level 2', minPay: 19900 },
  { name: 'જુનિયર કારકુન/જુ.કા કમ ટાઇપિસ્ટ/ટાઇપિસ્ટ', payLevel: 'Level 2', minPay: 19900 },
  { name: 'પ્રગતિ મદદનીશ', payLevel: 'Level 2', minPay: 19900 },
  { name: 'ગણક', payLevel: 'Level 2', minPay: 19900 },
  { name: 'ઇન્વેસ્ટિગેટર', payLevel: 'Level 2', minPay: 19900 },
  { name: 'લેબોરેટરી આસીસ્ટન્ટ', payLevel: 'Level 2', minPay: 19900 },
  { name: 'ડ્રાઇવર', payLevel: 'Level 2', minPay: 19900 },
  { name: 'સિનિયર કારકુન/જુનિયર ઓડિટર', payLevel: 'Level 4', minPay: 25500 },
  { name: 'સ્ટેનોગ્રાફર ગ્રેડ-૩', payLevel: 'Level 4', minPay: 25500 },
  { name: 'પ્રદર્શન મદદનીશ', payLevel: 'Level 4', minPay: 25500 },
  { name: 'પ્રોજેક્ટ ઓપરેટર', payLevel: 'Level 4', minPay: 25500 },
  { name: 'પશુધન નિરીક્ષક', payLevel: 'Level 4', minPay: 25500 },
  { name: 'ડેરી આસીસ્ટન્ટ', payLevel: 'Level 4', minPay: 25500 },
  { name: 'રેફ્રિજરેટર ઓપરેટર', payLevel: 'Level 4', minPay: 25500 },
  { name: 'બોઇલર ઓપરેટર', payLevel: 'Level 4', minPay: 25500 },
  { name: 'મદદનીશ કલાકાર (આર્ટિસ્ટ)', payLevel: 'Level 5', minPay: 29200 },
  { name: 'વિસ્તરણ અધિકારી (પશુપાલન)', payLevel: 'Level 5', minPay: 29200 },
  { name: 'આંકડા ઇન્સ્પેકટર', payLevel: 'Level 5', minPay: 29200 },
  { name: 'આંકડા મદદનીશ', payLevel: 'Level 5', minPay: 29200 },
  { name: 'આંકડા નિરીક્ષક', payLevel: 'Level 5', minPay: 29200 },
  { name: 'ઘાસચારા વિકાસ મદદનીશ', payLevel: 'Level 5', minPay: 29200 },
  { name: 'ખેતી નિરીક્ષક', payLevel: 'Level 5', minPay: 29200 },
  { name: 'ડેરી વિકાસ મદદનીશ', payLevel: 'Level 5', minPay: 29200 },
  { name: 'ગ્રેજ્યુએટ આસીસ્ટન્ટ', payLevel: 'Level 5', minPay: 29200 },
  { name: 'લેબોરેટરી ટેકનિશિયન', payLevel: 'Level 5', minPay: 29200 },
  { name: 'ઇલેક્ટ્રિક કમ મિકેનિક', payLevel: 'Level 5', minPay: 29200 },
  { name: 'મુખ્ય કારકુન / હિસાબનીશ', payLevel: 'Level 6', minPay: 29200 },
  { name: 'કચેરી અધિક્ષક/ ઓડિટર', payLevel: 'Level 7', minPay: 39900 },
  { name: 'સ્ટેનોગ્રાફર ગ્રેડ-૨', payLevel: 'Level 7', minPay: 39900 },
  { name: 'સંશોધન મદદનીશ', payLevel: 'Level 7', minPay: 39900 },
  { name: 'તાંત્રિક મદદનીશ', payLevel: 'Level 7', minPay: 39900 },
  { name: 'પશુચિકિત્સા અધિકારી', payLevel: 'Level 8', minPay: 44900 },
  { name: 'મદદનીશ વહીવટી અધિકારી', payLevel: 'Level 8', minPay: 44900 },
  { name: 'હિસાબી અધિકારી', payLevel: 'Level 8', minPay: 44900 },
  { name: 'આંકડા અધિકારી / ફિલ્ડ ઓફિસર / સંશોધન અધિકારી', payLevel: 'Level 8', minPay: 44900 },
  { name: 'મદદનીશ પશુપાલન નિયામક', payLevel: 'Level 9', minPay: 53100 },
  { name: 'વહીવટી અધિકારી', payLevel: 'Level 10', minPay: 56100 },
  { name: 'નાયબ નિયામક (મોજણી)', payLevel: 'Level 11', minPay: 67700 },
  { name: 'નાયબ નિયામક (આંકડા સંવર્ગ)', payLevel: 'Level 11', minPay: 67700 },
  { name: 'નાયબ નિયામક (હિસાબ)', payLevel: 'Level 11', minPay: 67700 },
  { name: 'નાયબ પશુપાલન નિયામક', payLevel: 'Level 11', minPay: 67700 },
  { name: 'સંયુક્ત પશુપાલન નિયામક', payLevel: 'Level 12', minPay: 78800 },
  { name: 'અધિક પશુપાલન નિયામક', payLevel: 'Level 13', minPay: 118500 },
  { name: 'પશુપાલન નિયામક', payLevel: 'Level 13 A', minPay: 131100 },
  { name: 'ઊંટ ચારક', payLevel: 'IS, 1', minPay: 14800 },
  { name: 'હેચરી આસીસ્ટન્ટ', payLevel: 'Level 4', minPay: 25500 },
];
